### ISSUE TITLE
How to set strings/factors in `experiment()`?

### ISSUE THREAD

**Issue by Z3tt** [nldoc/nlrx#2]
Thanks for this incredibly easy way to call NetLogo from R, what a nice improvement of the hustle of RNetLogo. 

However, I struggle to enter strings or factors as **variables** when setting up an experiment using the `experiment()` command. The documentation says that "Each list item consist of a min value, a max value, a step value and a qfun (e.g. list("paramA" = list(min=0, max=1, step=0.1, qfun="qunif")))" which is not the case for strings/factors. Every way putting the strings in a list did result in an error asking for `'from' must be of length 1`.

Is there a way to set up strings/factors as input variables?

**Comment by nldoc** [comment]
Currently, the variables slot only takes numeric inputs. When I implemented this, I only had sensitivity analyses in mind, which of course only work properly for numeric parameters. However, at least for the simple and full factorial simdesign it would be theoretical possible to include strings as parameter values. Thus, I plan to implement an option which allows to also supply discrete values for parameters within the variables slot. Instead of defining min, max, step and a qfun you could then just provide distinct values. I hope to get this implemented in the next days.

**Comment by Z3tt** [comment]
Hi, thanks for your effort! I got your point but from what I've learned it
a full sensitivity analysis should be also possible with a combination of
both, numeric and factorial variables. Would be great if the lhs sampling
would still l work when using factors (very nice btw to implement those
different in the package, thumbs up).

**Comment by nldoc** [comment]
Please check out the latest update. But please note that not all functions are tested thoroughly. I am still working on the latest updates. For the simdesign_ff it is now also possible to provide distinct values for each variable (further details, see readme of this repository). This also supports categorical values, such as strings. I also added a new simdesign (simdesign_distinct). For this simdesign you define a vector of n values for each variable. The parameter matrix then combines all first items of these vectors to one parameterisation, then all second items, and so on. This also supports categorical values.

However, I am still struggling with the ctagorical lhs. It would be possible by transforming the distributions to distinct factor levels but this seems not to be straightforward. As a quick fix, you could manage this within your NetLogo model. Just create numeric sliders on your GUI and add them to the variables of your experiment. In your NetLogo model you can then set your factors based on these numeric values.

**Comment by nldoc** [comment]
There is an escaped quote missing for your LOW variable list(values=c("\"LOW", "\"HIGH\"")).

**Comment by Z3tt** [comment]
Damn, I knew it would be something ridiculously simple... -.- Nevertheless, thank you very much! It is running as expected now!
